version: 2
jobs:
  test:
    docker:
      - image: linuxbrew/debian
    steps:
      - checkout
      - run: brew install Formula/vcn.rb && vcn verify $(which vcn)
workflows:
  version: 2
  test:
    jobs:
      - test
