version: 2
jobs:
  test:
    docker:
      - image: linuxbrew/alpine
    steps:
      - checkout
      - run: |
        brew update  
        brew cleanup
        brew install Formula/vcn.rb
workflows:
  version: 2
  test:
    jobs:
      - test
